### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by davidanthoff** [FugroRoames/TypedTables.jl#19]
Are there any plans to make this package work on julia 0.7?

I have no need for it, just want to know whether I should plan to keep it integrated with [TableTraits.jl](https://github.com/davidanthoff/TableTraits.jl) and the whole [Query.jl](https://github.com/davidanthoff/Query.jl) story or not.

**Comment by andyferris** [comment]
Great question!

I’d say “not in this current form” is the answer. I’d love to stay integrated in the future! I hope to have something even simpler than MinimumViableTables soon. This might replace this code or live elsewhere and should definitely become queryverse compatible ;)

**Comment by davidanthoff** [comment]
Cool!

MinimumViableTables probably is already mostly compatible. If it iterates named tuples, then we are game. We might need a little bit of glue code to consume other TableTraits.jl tables, but that should also be simple. Let me know when things are stable enough to start testing this in a more systematic way.

For now, I'll keep the TypedTables.jl integration on julia 0.6, but will remove it on julia 0.7.

**Comment by andyferris** [comment]
So the rewrite is merged.

Over the next days I hope we sort out the Tables.jl interface and get this hooked into Query as well. From their the roadmap is to improve basic functionality, speed, composability.

**Comment by andyferris** [comment]
I think at this stage, everything is "working" and integrated with Tables.jl, and therefore I believe Query??

Please open additional issues if anything doesn't work as expected!

**Comment by davidanthoff** [comment]
No, the current version won't work with the Queryverse. You'll need to replicate [this kind of code](https://github.com/JuliaData/DataFrames.jl/blob/master/src/other/tables.jl) here.

Or, if you are ok with taking a dependency on [DataValues.jl](https://github.com/queryverse/DataValues.jl), you could also use [TableTraitsUtils.jl](https://github.com/queryverse/TableTraitsUtils.jl) for the TableTraits.jl integration, which I think would make the integration code you need here in the package simpler.

**Comment by davidanthoff** [comment]
I do think you need the stuff in the constructor as well, if you want to use the file IO stuff in queryverse or materialize a query into a typed table, it will only work if the constructors here can consume a table that implements the TableTraits.jl interface.
