### ISSUE TITLE
Defining a row

### ISSUE THREAD

**Issue by JoshChristie** [FugroRoames/TypedTables.jl#2]
I'm getting an error when defining a row with predefined fields.
```
julia> @field(A::Int64)
A::Int64

julia> @field(B::Int64)
B::Int64

julia> @row(A=1, B=1)
ERROR: FieldIndex was expecting a Field tuple, but received (1,B::Float64)
 in error at ./error.jl:21
 in call at /home/josh/.julia/v0.4/TypedTables/src/FieldIndex.jl:10
```

**Comment by andyferris** [comment]
Oooh I'll have a look at that now. I actually am trying to fix another
macro bug this morning so this is good.

The "new" version (which is currently a mythical futuristic thing) will let
you just type the name and infer the type from the RHS, so I think that
will let you skip the first two lines.

Andy

**Comment by JoshChristie** [comment]
Thanks andy for the heads up. I didn't assign the fields.
```
A = @field(A::Int64)
B = @field(B::Int64)
R = @row(A=1, B=1)
```

**Comment by andyferris** [comment]
OK the persistent storage issue should be fixed. Update the package and let
me know if it works or not, please.

Andy
