### ISSUE TITLE
Type asserts conflict with missing values

### ISSUE THREAD

**Issue by GlenHertz** [FugroRoames/TypedTables.jl#25]
For example:
```
julia> v = NamedTuple{(:a, :b),Tuple{String, Union{Missing,Float64}}}[(a="a", b=44.5), (a="a2", b=missing)]
julia> t = Table(v)
ERROR: TypeError: in isassigned, in typeassert, expected NamedTuple{(:a, :b),Tuple{String,Union{Missing, Float64}}}, got NamedTuple{(:a, :b),Tuple{String,Float64}}
julia> rows(t)[1]
ERROR: TypeError: in isassigned, in typeassert, expected NamedTuple{(:a, :b),Tuple{String,Union{Missing, Float64}}}, got NamedTuple{(:a, :b),Tuple{String,Float64}}
```

The issue is the type of the row will become more specific (eg `Tuple{String,Float64}` and fail the typeassert of `map`:

```
@inline function Base.getindex(t::Table{T}, i::Int) where {T}
    @boundscheck checkbounds(t, i)
    map(col -> @inbounds(getindex(col, i)), columns(t))::T
end
```

How are missing values supposed to be handled?

**Comment by andyferris** [comment]
Very good question. Thanks for the report. 

I typically construct tables as `Table(a = [“a”, “a2”], b = [44.5, missing])`. But in either case that type assertion may bite you. 

It’s probably just an addition of a `<:` into the type assertion for getindex (and setindex!). It’s sometimes hard to remember that tuples are covariant but named tuples are invariant. :)

**Comment by andyferris** [comment]
OK I have pushed a fix for this. It should be efficient when there is a small number of Union columns.
