### ISSUE TITLE
CI busted on v1.0

### ISSUE THREAD

**Issue by andyferris** [FugroRoames/TypedTables.jl#28]
I haven't configured the CI correctly. This needs fixing.

**Comment by rafaqz** [comment]
TypedTables was  breaking my CI too.

Removing Project.toml makes everything work. I think it's something to do with specifying the version as 1.0.0-dev

**Comment by andyferris** [comment]
Thanks for the tip! I'm still a bit confused by the exact requirements of the new files for pkg3.

**Comment by rafaqz** [comment]
Me too!

Now TypedTables works SplitApplyCombine is giving me CI issues, I think I'll put that package on hold for a few weeks until the dust settles...

**Comment by andyferris** [comment]
Sorry to hear that.

I should have time to clean things up a bit next week.

**Comment by rafaqz** [comment]
No worries I got it all working in the end, I wasn't pulling SplitApplyCombine from Master.

**Comment by andyferris** [comment]
OK I think CI will pass as soon as the new SplitApplyCombine tag merges.

**Comment by andyferris** [comment]
Seems all good now.
