### ISSUE TITLE
Support for Tables.materializer

### ISSUE THREAD

**Issue by oschulz** [FugroRoames/TypedTables.jl#40]
Currently `materializer(::TypedTable)` returns the default `Tables.columntable`, so

    materializer(table)(columns(table)) 

currently returns a `NamedTuple` instead of a `TypedTables.Table`. A specialized method of `materializer` for `TypedTable` could be quite useful.

**Comment by oschulz** [comment]
It's fairly recent, I think:

    https://github.com/JuliaData/Tables.jl#functions-that-input-and-output-tables

From what I understand, it allows for writing generic functions that transform a table into a new table of the same kind, and only have the `Tables` package as a dependency.

I guess it could simply be

    materializer(::TypedTables.TypedTable) = TypedTables.TypedTable

**Comment by andyferris** [comment]
Ah! It’s solving the same problem as `propertytype` on my open PR branches.

**Comment by oschulz** [comment]
So what do you think, should we add this?

**Comment by andyferris** [comment]
Yes, we should add these two lines to the Table.jl and FlexTable.jl files respectively.

```julia
Tables.materializer(::Table) = Table
Tables.materializer(::FlexTable) = FlexTable
```

**Comment by andyferris** [comment]
Thanks Oliver!
